defaults:
  - attack_method: pgd_a0.0001.yaml
  - ckpt: lift_ph_cnn_best

attack_config:
  shape: [3, 17, 17]
  random_start: True
  ntarget: null
  attacked_obs:
    agentview_image:
      train_tf:
        _target_: diffusion_policy.attack.CustomRandomAffine.CustomRandomAffine
        degrees: [-45, 45]
        translate: [-0.4, 0.4, -0.4, 0.4]
        shear: [-50, 50, -50, 50]
        p: 1.
      val_tf:
        _target_: diffusion_policy.attack.CustomRandomAffine.CustomRandomAffine
        degrees: 0
        translate: [-0.3, -0.3, 0.2, 0.2]
        p: 1.
        


task_name: ${ckpt.task_name}
arch: ${ckpt.backbone_arch}
dataset_type: ${ckpt.ds_type}
attack_type: ${attack_method.name}
alpha: ${attack_method.alpha}
batch_size: ${attack_method.batch_size}
name: ${now:%Y.%m.%d-%H.%M.%S}_${task_name}_${dataset_type}_${arch}
dataloader:
  batch_size: ${attack_method.batch_size}
  num_workers: 16
  shuffle: true
  pin_memory: true
  persistent_workers: false
val_dataloader:
  batch_size: ${attack_method.batch_size}
  num_workers: 16
  shuffle: false
  pin_memory: true
  persistent_workers: false
training:
  device: cuda:0
  seed: 77
  debug: false
  resume: true
  num_epochs: 26
  rollout_every: 25
  val_every: 25
  sample_every: 25
  checkpoint_every: 100
  max_train_steps_per_e: null
  max_val_steps_per_e: null
  max_train_steps: null
  tqdm_interval_sec: 1.0
logging:
  project: physical_attack_diffusion_policy_train
  resume: true
  mode: online
  name: ${name}
  tags:
  - ${task_name}
  - ${arch}_${dataset_type}
  - ${attack_type}
  id: null
  group: null


hydra:
  job:
    override_dirname: ${task_name}
  run:
    dir: data/outputs/physical_attack_train/${now:%Y.%m.%d}/${now:%H.%M.%S}_${task_name}_${arch}_${attack_type}
  sweep:
    dir: data/outputs/physical_attack_train/${now:%Y.%m.%d}/${now:%H.%M.%S}_${task_name}_${arch}_${attack_type}
    subdir: ${hydra.job.num}